- .github/CODEOWNERS
- README.md
Added codeowners and also updated maintainer info, cc @chapulina @nkoenig 
> Add codeowners

- .github/CODEOWNERS
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Port `CODEOWNERS`
> [ign-sensors3] Workflow updates

- .github/CODEOWNERS
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Port `CODEOWNERS`
> [ign-sensors2] Workflow updates

- BUILD.bazel
- src/SensorFactory.cc
- test/BUILD.bazel
All tests passing
Signed-off-by: John Shepherd <john@openrobotics.org>
> [Bazel] Sensors bazel build scripts

- BUILD.bazel
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Tweaks to support physics in ign-gazebo

- CMakeLists.txt
- Changelog.md
> 2.9.0 release prep

- CMakeLists.txt
- Changelog.md
- Migration.md
Update dependency needed since #41, add migration and changelog.
Diff from `ign-sensors3`:
https://github.com/ignitionrobotics/ign-sensors/compare/ign-sensors3...master
> Bump ign-math to 6.6, add migration and changelog

- README.md
Libraries link was missing '.org'
> Corrected link address

- CMakeLists.txt
- Changelog.md
> Prepare for 4.0.0 release

- .github/ci/packages.apt
- CMakeLists.txt
- examples/save_image/CMakeLists.txt
Bump `ign-rendering`.
See https://github.com/ignition-tooling/release-tools/issues/331
> Bump in edifice: ign-rendering5

- src/PointCloudUtil.cc
This PR is meant to resolve new codecheck issues introduced by https://github.com/ignitionrobotics/ign-cmake/pull/117.
From my understanding, the plan is to forward port the fixes here to all other ignition versions once https://github.com/ignitionrobotics/ign-cmake/pull/117 is merged.
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
> Resolve updated codecheck issues

- .github/workflows/macos.yml
- include/ignition/sensors/Lidar.hh
- src/GpuLidarSensor.cc
- src/Lidar.cc
> 3 to 4 20210208

- Changelog.md
> 3 to 4 20210211

- CMakeLists.txt
- Changelog.md
4.1.0 release
https://github.com/ignitionrobotics/ign-sensors/compare/ignition-sensors4_4.0.0...ign-sensors4
> 4-1-0 prep

- .github/ci/packages.apt
- .github/workflows/macos.yml
- CMakeLists.txt
- bitbucket-pipelines.yml
- src/Sensor.cc
Addresses https://github.com/ignition-tooling/release-tools/issues/361
> Bump in edifice: ign-common4

- CMakeLists.txt
- Changelog.md
- include/ignition/sensors/Lidar.hh
- src/GpuLidarSensor.cc
- src/Lidar.cc
- src/Lidar_TEST.cc
> Revert "Apply noise evenly to scans and point clouds (#89)" and prep for 5.0.0~pre2

- test/integration/gpu_lidar_sensor_plugin.cc
- test/integration/rgbd_camera_plugin.cc
Port `ign-sensors3` to `ign-sensors4`.
Branch comparison: https://github.com/ignitionrobotics/ign-sensors/compare/ign-sensors4...ign-sensors3
https://github.com/osrf/buildfarmer/issues/181
> 👩‍🌾 3 ➡️ 4

- Changelog.md
Quick changelog fix spotted during https://github.com/ignitionrobotics/ign-sensors/pull/125#discussion_r619483578
> Changelog fix

- include/ignition/sensors/AirPressureSensor.hh
- include/ignition/sensors/AltimeterSensor.hh
- include/ignition/sensors/CameraSensor.hh
- include/ignition/sensors/DepthCameraSensor.hh
- include/ignition/sensors/GpuLidarSensor.hh
- include/ignition/sensors/ImuSensor.hh
- include/ignition/sensors/Lidar.hh
- include/ignition/sensors/LogicalCameraSensor.hh
- include/ignition/sensors/MagnetometerSensor.hh
- include/ignition/sensors/Manager.hh
- include/ignition/sensors/RgbdCameraSensor.hh
- include/ignition/sensors/Sensor.hh
- include/ignition/sensors/ThermalCameraSensor.hh
- src/AirPressureSensor.cc
- src/AltimeterSensor.cc
- src/CMakeLists.txt
- src/CameraSensor.cc
- src/DepthCameraSensor.cc
- src/GpuLidarSensor.cc
- src/ImuSensor.cc
- src/Lidar.cc
- src/LogicalCameraSensor.cc
- src/MagnetometerSensor.cc
- src/Manager.cc
- src/RgbdCameraSensor.cc
- src/Sensor.cc
- src/Sensor_TEST.cc
- src/ThermalCameraSensor.cc
- test/integration/gpu_lidar_sensor_plugin.cc
- test/integration/logical_camera_plugin.cc
Perform the tock of the tick-tock.
> Remove deprecations: tock

- Changelog.md
Preparation for <6.0.0~pre1> release.
Comparison to <5.0.0>: https://github.com/ignitionrobotics/ign-sensors/compare/ign-sensors5...main
Needed by ignitionrobotics/ign-gazebo#977 ignitionrobotics/ign-gazebo#853
> 6.0.0~pre1

- CMakeLists.txt
- Changelog.md
- README.md
Preparation for 6.0.0 release.
Comparison to 5: https://github.com/ignitionrobotics/ign-sensors/compare/ign-sensors5...ign-sensors6
ignition-tooling/release-tools#459
> Prepare for 6.0.0 release

- tutorials/install.md
Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>
Added macOS install instructions
> Added macOS install instructions

- .github/ci/packages.apt
- CMakeLists.txt
- examples/save_image/CMakeLists.txt
See https://github.com/ignition-tooling/release-tools/issues/545
> Bumps in garden : ign-sensors7

- .github/ci/packages.apt
- CMakeLists.txt
See https://github.com/ignition-tooling/release-tools/issues/554
> Bumps in garden : ci_matching_branch/bump_garden_ign-sensors7

- .github/ci/packages.apt
- CMakeLists.txt
- include/ignition/sensors/ForceTorqueSensor.hh
- include/ignition/sensors/SegmentationCameraSensor.hh
- src/Sensor_TEST.cc
See https://github.com/ignition-tooling/release-tools/issues/574
Requires
* https://github.com/ignitionrobotics/sdformat/pull/805
* https://github.com/ignitionrobotics/sdformat/pull/803
* https://github.com/ignitionrobotics/ign-rendering/pull/525
> Bumps in garden: ign-math7, ign-common5, sdformat13

- CMakeLists.txt
- Changelog.md
- Migration.md
- include/ignition/sensors/NavSatSensor.hh
- include/ignition/sensors/SensorTypes.hh
- src/CMakeLists.txt
- src/GpuLidarSensor.cc
- src/ImuSensor.cc
- src/ImuSensor_TEST.cc
- src/NavSatSensor.cc
- test/integration/CMakeLists.txt
- test/integration/gpu_lidar_sensor.cc
- test/integration/navsat.cc
Port `ign-sensors6` to `main`
Branch comparison: https://github.com/ignitionrobotics/ign-sensors/compare/main...ign-sensors6
* Requires https://github.com/ignitionrobotics/ign-msgs/pull/213
* Required by https://github.com/ignitionrobotics/ign-gazebo/pull/1293
> 6 ➡️ 7 (main)

- include/ignition/sensors/AirPressureSensor.hh
- include/ignition/sensors/AltimeterSensor.hh
- include/ignition/sensors/CameraSensor.hh
- include/ignition/sensors/DepthCameraSensor.hh
- include/ignition/sensors/ForceTorqueSensor.hh
- include/ignition/sensors/GpuLidarSensor.hh
- include/ignition/sensors/ImuSensor.hh
- include/ignition/sensors/Lidar.hh
- include/ignition/sensors/LogicalCameraSensor.hh
- include/ignition/sensors/MagnetometerSensor.hh
- include/ignition/sensors/Manager.hh
- include/ignition/sensors/NavSatSensor.hh
- include/ignition/sensors/RenderingEvents.hh
- include/ignition/sensors/RenderingSensor.hh
- include/ignition/sensors/RgbdCameraSensor.hh
- include/ignition/sensors/SegmentationCameraSensor.hh
- include/ignition/sensors/Sensor.hh
- include/ignition/sensors/SensorFactory.hh
- include/ignition/sensors/ThermalCameraSensor.hh
- include/ignition/sensors/WideAngleCameraSensor.hh
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Change to use SuppressWarning from ign-utils

- .github/workflows/ci.yml
- src/CMakeLists.txt
Enable cpplint checking in GitHub actions CI
Look at results of GitHub actions CI jobs
> Enable cpplint check in github actions CI

- CMakeLists.txt
- Changelog.md
Signed-off-by: Aditya <aditya050995@gmail.com>
Preparation for 6.3.0 release.
Comparison to 6.2.0 : https://github.com/ignitionrobotics/ign-sensors/compare/ign_sensors6_6.2.0...aditya/6.3.0
Needed by :
https://github.com/ignitionrobotics/ign-gazebo/pull/1320
> Prepare for 6.3.0

- Changelog.md
- include/ignition/sensors/BrownDistortionModel.hh
- include/ignition/sensors/Distortion.hh
- include/ignition/sensors/ImageBrownDistortionModel.hh
- include/ignition/sensors/ImageDistortion.hh
- include/ignition/sensors/Sensor.hh
- include/ignition/sensors/SensorTypes.hh
- src/BrownDistortionModel.cc
- src/CMakeLists.txt
- src/CameraSensor.cc
- src/Distortion.cc
- src/ImageBrownDistortionModel.cc
- src/ImageDistortion.cc
- src/ImageGaussianNoiseModel.cc
- src/ImuSensor.cc
- src/ImuSensor_TEST.cc
- test/integration/CMakeLists.txt
- test/integration/distortion_camera.cc
- test/integration/triggered_camera.cc
- test/sdf/distortion_camera_sensor_builtin.sdf
- test/sdf/triggered_camera_sensor_builtin.sdf
Port `ign-sensors6` to `main`
Branch comparison: https://github.com/ignitionrobotics/ign-sensors/compare/main...ign-sensors6
> Merge 6 -> main

- Migration.md
- examples/custom_sensor/Odometer.cc
- examples/loop_sensor/sensors.sdf
- test/sdf/custom_sensors.sdf
- tutorials/custom_sensors.md
- tutorials/segmentation_camera.md
- tutorials/thermal_camera.md
See: https://github.com/gazebo-tooling/release-tools/issues/744
> ign -> gz Shared Lib Migration : gz-sensors

- CMakeLists.txt
- api.md.in
- include/ignition/sensors/config.hh.in
- test/integration/all_symbols_have_version.bash.in
- tutorials.md.in
I ran `find . -name "*" -exec -i 's/IGN_DESIGNATION/GZ_DESIGNATION/g' {} \;` in order to make this repository compliant with https://github.com/gazebosim/gz-cmake/pull/282
> Change IGN_DESIGNATION to GZ_DESIGNATION

- CMakeLists.txt
- api.md.in
- include/ignition/sensors/config.hh.in
- test/integration/all_symbols_have_version.bash.in
- tutorials.md.in
This merges forward GZ_DESIGNATION updates from v1 to v2.
> 1 to 2 GZ_DESIGNATION

- CMakeLists.txt
- Changelog.md
- api.md.in
- include/ignition/sensors/config.hh.in
- test/integration/all_symbols_have_version.bash.in
- tutorials.md.in
Port `ign-sensors2 ` ➡️  `ign-sensors3`
Branch comparision: https://github.com/ignitionrobotics/ign-sensors/compare/ign-sensors3...ign-sensors2
> Merge ign-sensors2 ➡️  ign-sensors3

- src/AirPressureSensor.cc
- src/AltimeterSensor.cc
- src/CameraSensor.cc
- src/DepthCameraSensor.cc
- src/GaussianNoiseModel.cc
- src/ImuSensor.cc
- src/ImuSensor_TEST.cc
- src/LogicalCameraSensor.cc
- src/MagnetometerSensor.cc
- src/Manager.cc
- src/Noise_TEST.cc
- src/RgbdCameraSensor.cc
- src/SensorFactory.cc
- src/SensorTypes.cc
- src/Sensor_TEST.cc
- src/ThermalCameraSensor.cc
- test/integration/rgbd_camera_plugin.cc
Part of: https://github.com/gazebo-tooling/release-tools/issues/784
> ign -> gz : Remove redundant namespace references

- tutorials/thermal_camera.md
> Fix link in thermal camera tutorial

- test/integration/triggered_camera.cc
> Fixed INTEGRATION triggered_camera test

- tutorials/install.md
Fix and improve installation documentation. Related https://github.com/gazebosim/garden-tutorial-party/issues/548
> Fix and improve installation documentation

- tutorials/thermal_camera.md
Improved thermal camera tutorial. Related with https://github.com/gazebosim/garden-tutorial-party/issues/573
> Improved thermal camera tutorial

- CMakeLists.txt
Preparation for 6.7.0 release.
Comparison to 6.6.0: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors6_6.6.0...ign-sensors6
> 6.7.0 release

- CMakeLists.txt
Port `ign-sensors6 ` ➡️  `gz-sensors7`
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/gz-sensors7...ign-sensors6
> Merge ign-sensors6 ➡️  gz-sensors7

- CMakeLists.txt
- include/gz/sensors/DepthCameraSensor.hh
- src/CameraSensor.cc
- src/DepthCameraSensor.cc
- src/GpuLidarSensor.cc
- src/NavSatSensor.cc
- src/SegmentationCameraSensor.cc
- src/Sensor.cc
Port `gz-sensors7 ` ➡️  `main`
Branch comparison: https://github.com/ignitionrobotics/ign-sensors/compare/main...gz-sensors7
> Merge gz-sensors7 ➡️  main

- CMakeLists.txt
- Changelog.md
Preparation for 6.7.1 release.
Comparison to 6.7.0: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors6_6.7.0...ign-sensors6
Needed by <PR(s)>
> Prepare for 6.7.1 Release

- tutorials/intro.md
https://github.com/gazebosim/gazebo_test_cases/issues/181
Fixes reference to gazebo classic
> Update reference to gazebo classic in introduction

- tutorials/thermal_camera.md
https://github.com/gazebosim/gazebo_test_cases/issues/187
Tweaks to links and instructions
> Minor updates to the thermal camera tutorial

- README.md
updated to use Jammy CI status badge and enabled project on jenkins 
> Use Jammy CI status badge in README

- .github/workflows/ci.yml
- .github/workflows/triage.yml
Port `ign-sensors3 ` ➡️  `ign-sensors6`
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/ign-sensors6...ign-sensors3
> Merge ign-sensors3 ➡️  ign-sensors6

- Changelog.md
Preparation for 8.0.1 release. Followup to #419 to add #420 
Comparison to 8.0.0: https://github.com/gazebosim/gz-sensors/compare/gz-sensors8_8.0.0...gz-sensors8
> Prepare for 8.0.1 Release (v2)

- Changelog.md
- include/gz/sensors/Sensor.hh
- src/BoundingBoxCameraSensor.cc
- src/CameraSensor.cc
- src/DepthCameraSensor.cc
- src/GpuLidarSensor.cc
- src/RgbdCameraSensor.cc
- src/SegmentationCameraSensor.cc
- src/Sensor.cc
- src/Sensor_TEST.cc
- src/ThermalCameraSensor.cc
- src/WideAngleCameraSensor.cc
➡️ Forward port
Fixes #440 for main branch
Port gz-sensors8 to main
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/main...gz-sensors8
> Merge 8 -> main

- src/DepthCameraSensor.cc
- src/GpuLidarSensor.cc
- src/RgbdCameraSensor.cc
Fixes clang-tidy missing include complaint
Include `gz/msgs/PointCloudPackedUtils.hh` for `gz::msgs::InitPointCloudPacked`.
> RgbdCameraSensor: add missing include

- README.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
> Update badges to point to gz-sensors9

- tutorials.md.in
- tutorials/boundingbox_camera.md
Fixes #<NUMBER>
This tutorial is currently missing from the list
> Add boundingbox_camera tutorial to the tutorials list

- CMakeLists.txt
- Changelog.md
Preparation for 9.0.0~pre2 release.
Comparison to 9.0.0~pre1: https://github.com/gazebosim/gz-sensors/compare/gz-sensors9_9.0.0-pre1...prep_9.0.0pre2
> Prepare for gz-sensors9.0.0~pre2 release

- CMakeLists.txt
- Changelog.md
- README.md
- tutorials.md.in
- tutorials/boundingbox_camera.md
- tutorials/custom_sensors.md
- tutorials/install.md
- tutorials/segmentation_camera.md
- tutorials/thermal_camera.md
Port gz-sensors9 to main
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/main...gz-sensors9
> Merge 9 -> main

- CMakeLists.txt
- Changelog.md
- README.md
- examples/custom_sensor/CMakeLists.txt
- examples/imu_noise/CMakeLists.txt
- examples/loop_sensor/CMakeLists.txt
- examples/save_image/CMakeLists.txt
- package.xml
Bump main to gz-sensors 10.0.0~pre1
> Bump main to sensors 10.0.0~pre1

- README.md
Simple link to the SDF specification. This is in relation to issue [103](https://github.com/gazebosim/gz-sensors/issues/103). This isn't the entire scope of what is asked in the original issue, however a link like this would've saved me an immense amount of time so I think this is much better than nothing.
> Update README.md - Link to SDF Spec

- Changelog.md
- README.md
- include/gz/sensors/LogicalCameraSensor.hh
- src/DepthCameraSensor.cc
- src/GpuLidarSensor.cc
- src/LogicalCameraSensor.cc
- src/RgbdCameraSensor.cc
- test/integration/gpu_lidar_sensor.cc
- test/integration/rgbd_camera.cc
Port `gz-sensors9 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/main...gz-sensors9
> Merge gz-sensors9 ➡️  main

- .github/ci/packages.apt
- .github/disabled_workflows/macos.yml
- .github/workflows/ci.yml
- CMakeLists.txt
- package.xml
- src/CMakeLists.txt
- tutorials/thermal_camera.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1292.
> Bump gz-transport and others in jetty

- .github/ci/packages.apt
- CMakeLists.txt
- examples/custom_sensor/CMakeLists.txt
- examples/save_image/CMakeLists.txt
- package.xml
- src/CMakeLists.txt
- src/CameraSensor.cc
- src/RgbdCameraSensor.cc
- tutorials/thermal_camera.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1309.
> Bump gz-cmake and others in jetty

- .github/workflows/bazel.yml
- README.md
- tutorials/boundingbox_camera.md
- tutorials/custom_sensors.md
Part of https://github.com/gazebosim/gz-jetty/issues/31
> Update references of main to gz-sensors10

- CMakeLists.txt
- Changelog.md
Preparation for 10.0.0 release.
Comparison to 10.0.0~pre1: https://github.com/gazebosim/gz-sensors/compare/gz-sensors10_10.0.0-pre1...gz-sensors10
> [DRAFT] Prepare for 10.0.0 release
