gazebosim/gz-sensors

.github/ci-bionic/after_make.sh, .github/workflows/ci-bionic.yml, CMakeLists.txt, test/integration/depth_camera_plugin.cc
As part of the works of ignition-tooling/gazebodistro#5 bump the use of msgs to major version 6, transport to 9, sdf to 10.
=> Update deps for Dome: use msgs6, transport9, sdf10

.github/ci/after_make.sh, .github/ci/packages.apt, .github/workflows/ci.yml, CMakeLists.txt, include/ignition/sensors/Sensor.hh, src/AirPressureSensor.cc, src/AltimeterSensor.cc, src/CameraSensor.cc, src/Camera_TEST.cc, src/DepthCameraSensor.cc, src/GpuLidarSensor.cc, src/ImuSensor.cc, src/Lidar.cc, src/LogicalCameraSensor.cc, src/MagnetometerSensor.cc, src/Sensor.cc, src/Sensor_TEST.cc, test/integration/air_pressure_plugin.cc, test/integration/altimeter_plugin.cc, test/integration/depth_camera_plugin.cc, test/integration/gpu_lidar_sensor_plugin.cc, test/integration/imu_plugin.cc, test/integration/logical_camera_plugin.cc, test/integration/magnetometer_plugin.cc
Requires https://github.com/ignitionrobotics/ign-transport/pull/153/
Addresses https://github.com/ignitionrobotics/ign-gazebo/issues/239
* Make sure all sensors have a default topic
* When invalid topics are passed in, convert them to valid topics if possible
* If not possible to convert into valid topic, fail gracefully
=> Make topics valid

src/Noise.cc, src/RgbdCameraSensor.cc
Depends on ignitionrobotics/ign-rendering#122
Applies noise to an RGBD camera sensor. The actual noise implementation is done in the ign-rendering pull request
=> Add noise to RGBD camera

src/CameraSensor.cc
Updated camera sensor to render and generate data only if there are subscribers or if it needs to save data to disk. This avoid unnecessary computation cost when the camera sensor is idle.
While testing I noticed that `this->dataPtr->pub.HasConnections()` reports correct value when I subscribe using `ign topic -e -t`. However, if I test with the `ImageDisplay` plugin in ign-gazebo, the `HasConnections` will always return true even after the plugin is closed. I verified that the ImageDisplay's destructor is called so maybe we're doing something wrong? cc @caguero 
=> Update camera sensor only when needed

include/ignition/sensors/Manager.hh, src/Camera_TEST.cc, src/ImuSensor_TEST.cc, src/Lidar_TEST.cc, src/Manager_TEST.cc, src/Noise_TEST.cc, src/Sensor_TEST.cc, test/integration/air_pressure_plugin.cc, test/integration/altimeter_plugin.cc, test/integration/camera_plugin.cc, test/integration/depth_camera_plugin.cc, test/integration/gpu_lidar_sensor_plugin.cc, test/integration/imu_plugin.cc, test/integration/logical_camera_plugin.cc, test/integration/magnetometer_plugin.cc, test/integration/rgbd_camera_plugin.cc, test/integration/thermal_camera_plugin.cc
This should help shed some light into #4 .
* Use `ASSERT_NE(nullptr...)` to prevent test segfaults
* Make all tests verbose to help debug issues
It looks like the sensor is created correctly, but the problem happens when casting the sensor to the desired type. Maybe there's a mismatch between the types from the core library and the sensor's shared library? I vaguely remember @ahcorde having a solution for this while working on #38, but I don't know if that solution works for Citadel.
CC @scpeters , who was looking into #4.
=> 👩‍🌾 Prevent segfaults on test failures, make tests verbose

.github/workflows/macos.yml, src/CMakeLists.txt, test/integration/CMakeLists.txt, test/integration/air_pressure_plugin.cc, test/integration/altimeter_plugin.cc, test/integration/camera_plugin.cc, test/integration/depth_camera_plugin.cc, test/integration/gpu_lidar_sensor_plugin.cc, test/integration/imu_plugin.cc, test/integration/logical_camera_plugin.cc, test/integration/magnetometer_plugin.cc, test/integration/rgbd_camera_plugin.cc, test/integration/thermal_camera_plugin.cc
This adds a GitHub actions workflow that uses macOS Catalina to help debug the `UNIT_Lidar_TEST` failures reported in #4. It turns out that all the windows test failures and most on macOS are caused by a failure to load sensor component libraries properly and can be fixed by properly setting environment variables for the tests.
In windows CI and the macOS workflow (which runs `make test` before `make install`) tests were failing with the message "Unable to find sensor plugin path". This is fixed by setting the `IGN_PLUGIN_PATH` in cmake to the build folder containing the compiled plugins.
In the macOS jenkins build (which runs `make test` after `make install`) tests were failing with the message "SDF sensor type does not match template type". It was difficult to track down, but it appears …
=> Fix macOS/windows tests that failed to load library

src/SensorFactory.cc
Similar to https://github.com/ignitionrobotics/ign-math/pull/183.
---
I'm building in Focal, this PR fixes some "-Wno-pessimizing-move" warnings (which does not happen with the gcc version in Bionic).
From [here](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/C_002b_002b-Dialect-Options.html):
```
-Wno-pessimizing-move (C++ and Objective-C++ only)
This warning warns when a call to std::move prevents copy elision. A typical scenario when copy elision can occur is when returning in a function with a class return type, when the expression being returned is the name of a non-volatile automatic object, and is not a function parameter, and has the same type as the function return type.
struct T {
…
};
T fn()
{
T t;
…
return std::move (t);
}
But in this example, the std::move call prevents copy …
```
=> Avoid moving a return value, it might prevent (N)RVO

CMakeLists.txt, Changelog.md
Preparing for a last major version 2 release before Blueprint EOLs in 8 days.
Comparison to 2.9.0:
https://github.com/ignitionrobotics/ign-sensors/compare/ignition-sensors2_2.9.0...ign-sensors2
There are no PRs open against `ign-sensors2`.
=> ⬆️  2.9.1 🏁

.github/ci/packages.apt, CMakeLists.txt
Addresses https://github.com/ignition-tooling/release-tools/issues/362
=> Bump in edifice: ign-msgs7

README.md, tutorials/02_install.md
Retargeting https://github.com/ignitionrobotics/ign-sensors/pull/71 to Citadel
=> Add Windows Installation

include/ignition/sensors/Lidar.hh, src/GpuLidarSensor.cc, src/Lidar.cc
Noise was not applied to the point cloud generated by the GpuLidarSensor. This change applies noise to the `laserBuffer`, which then used by both the `scan` and `point cloud` topics.
=> Apply noise to lidar point cloud

CMakeLists.txt, Changelog.md
https://github.com/ignitionrobotics/ign-sensors/compare/ignition-sensors3_3.1.0...ign-sensors3
=> Prepare fo 3.2.0 release

src/CMakeLists.txt, src/Sensor.cc, src/Sensor_TEST.cc
Helps with issue #81 and https://github.com/osrf/subt/issues/680 (for some users).
This PR adds an Ignition Transport service `~/set_rate` to all sensors. This is to allow users to selectively slow down some sensors if they do not need them running at full rate. This is extremely helpful with rendering sensors when you can anyways process only 6 Hz or similar, but the sensors run on 30.
I also made the service check if the caller doesn't want to set a higher rate than the value of `<update_rate>` in the sensor's SDF. Such attempts are ignored (with the exception of zero update rate in SDF, which allows to set any rate via this service).
I added a unit test and also tested it running the SubT simulator with EXPLORER_X1_SENSOR_CONFIG_2. This robot has 4 RGBD cameras, and the set_rate …
=> Add set_rate service to all sensors

src/Sensor.cc, src/ThermalCameraSensor.cc, test/integration/thermal_camera_plugin.cc, test/integration/thermal_camera_sensor_8bit_builtin.sdf, test/integration/thermal_camera_sensor_builtin.sdf
Depends on ~~https://github.com/ignitionrobotics/ign-rendering/pull/235~~
Adds the necessary hooks to set ign-rendering thermal camera sensor to 8 bit image format and publish the generated image data.
Note that ign-rendering still returns `uint16_t` in the image callback but it actually contains 8 bit data. This was done to avoid breaking ABI. However, the image that's published by ign-sensors will have the correct format in a 8 bit unsigned char array
=> Add support for 8 bit thermal camera image format

src/CMakeLists.txt, test/integration/CMakeLists.txt, test/integration/air_pressure_plugin.cc, test/integration/altimeter_plugin.cc, test/integration/camera_plugin.cc, test/integration/depth_camera_plugin.cc, test/integration/gpu_lidar_sensor_plugin.cc, test/integration/imu_plugin.cc, test/integration/logical_camera_plugin.cc, test/integration/magnetometer_plugin.cc, test/integration/rgbd_camera_plugin.cc, test/integration/thermal_camera_plugin.cc
This backports #60 except the macOS workflow. 
**Note to maintainers**: Remember to use **Rebase and merge**
=> Backport of #60: Fix macOS/windows tests that failed to load library

README.md, examples/imu_noise/README.md, examples/imu_noise/main.cc
Improved Windows instructions and I made some changes to compile the examples on Windows
=> Improved Windows instructions

.github/workflows/macos.yml, CMakeLists.txt, Changelog.md, examples/imu_noise/CMakeLists.txt, examples/save_image/CMakeLists.txt
Branch `ign-sensors5` has been created for the Edifice release and 5.0.0 released from that.
The `main` branch now corresponds to version 6.0.0~pre1, and nightlies will soon be created from this branch.
https://github.com/ignition-tooling/release-tools/issues/421
=> Bump main to 6.0.0~pre1

.github/ci/packages.apt, CMakeLists.txt, examples/save_image/CMakeLists.txt
See https://github.com/ignition-tooling/release-tools/issues/428
=> Bumps in fortress : ign-sensors6

test/integration/gpu_lidar_sensor_plugin.cc, test/integration/rgbd_camera_plugin.cc
See #66 and #67
These tests are known to fail on macOS consistently. We should disable tests in such cases, so that CI's regular state is green and new test failures are easier to spot.
I opted for just disabling the offending lines instead of the entire test because most of the expectations succeed.
Once this is in, we can make Homebrew CI checks required to merge PRs.
https://github.com/osrf/buildfarmer/issues/181
=> 👩‍🌾 Disable tests that consistently fail on macOS

src/Lidar.cc
Fixes #131
This PR removes clamping from application of lidar noise. The clamping generates wrong points for missed rays, as it clamps even the +-Inf values to the lidar range. Removing the clamping might lead to having some points with distance larger than `range_max` of the sensor, but I'd argue that's okay in case of noise. If not, then the code should explicitly check to not clamp infinite values.
=> Remove clamping from lidar noise

include/ignition/sensors/Sensor.hh, src/Sensor.cc
I needed a way to reset the `nextUpdateTime` to zero when seeking backward in a log file. Modifying `::Init` seemed convenient and unlikely to affect anyone. I can make a new function to accomplish the same goal if that is perferred.
=> Init will now set the nextUpdateTime to zero

include/ignition/sensors/ImuSensor.hh, src/ImuSensor.cc, src/ImuSensor_TEST.cc
Not all IMUs produce orientation estimates. This PR adds a new API to the IMU sensor class to allow users to disable computing and publishing orientation values.
=> Add API for enabling / disabling IMU orientation

src/RenderingSensor.cc, test/integration/gpu_lidar_sensor_plugin.cc
See ignitionrobotics/ign-rendering/issues/323
ign-rendering has a new feature aimed to improve performance but also fixes a few bugs related to particle simulations; which is controlled via `Scene::SetCameraPassCountPerGpuFlush`.
A value of 0 will use the legacy mode (i.e. previous behavior) to ease porting from older version.
A value > 0 controls performance vs RAM tradeoff (note that it is an upper limit; a very high value doesn't immediately waste RAM. See `Scene::SetCameraPassCountPerGpuFlush` documentation for details)
These changes makes sensors aware of legacy and new setting so that it adapts to both modes of operation.
This PR depends on https://github.com/ignitionrobotics/ign-rendering/pull/353 **otherwise it will not compile**.
Just run the code again. This PR changes …
=> Make Sensors aware of CameraPassCountPerGpuFlush & Scene::PostFrame

examples/custom_sensor/CMakeLists.txt, examples/custom_sensor/CustomSensor.cc, examples/custom_sensor/CustomSensor.hh, examples/custom_sensor/README.md, examples/custom_sensor/custom_sensor.sdf, examples/loop_sensor/CMakeLists.txt, examples/loop_sensor/README.md, examples/loop_sensor/altimeter_example.sdf, examples/loop_sensor/main.cc, include/ignition/sensors/Sensor.hh, src/SensorFactory.cc
Closes #9
Builds on top of #90 
Add support for custom sensors that aren't installed together with `ign-sensors`, so that external users can implement their own sensors. This adds:
* The environment variable `IGN_SENSORS_PATH` that users can set to find sensors.
* An example with a custom sensor
* An example with an executable that can loop any non-rendering sensor, and can be used to test the custom sensor
It also makes the deprecated `Update` function non-pure-virtual, so downstream developers aren't forced to implement a deprecated function. 
I decided to work on this to validate that the work being done on #90 was flexible enough to support external sensors.
Follow the instructions on each example's READMEs.
=> Support custom sensors

include/ignition/sensors/Sensor.hh, src/Sensor.cc, src/Sensor_TEST.cc
Signed-off-by: Franco Cipollone <franco.c@ekumenlabs.com>
Related to https://github.com/ignitionrobotics/ign-gazebo/issues/557
- `ignition::sensors::Sensor` publishes a performance metric message (`ignition::msgs::PeformanceSensorMetrics`)
for each Update() call. The message is published at `<sensor_topic_name>/performance_metrics`
-  This message is being added to the `ignition-msgs` in PR: https://github.com/ignitionrobotics/ign-msgs/pull/172
- Publishing performance metrics can be disabled trough sdf: https://github.com/ignitionrobotics/sdformat/pull/665   
```proto
message PerformanceSensorMetrics
{
/// \brief Sensor name
string name                 = 1;
/// \brief The update rate of the sensor in real time.
double real_update_rate     = 2;
/// \brief The update rate of the sensor in …
```
=> Publish performance sensor metrics.

test/test_config.h.in
see https://github.com/ignitionrobotics/ign-rendering/pull/407 for more info. 
Switching to ogre 1.x on macos for ignition Fortress libraries
=> Update test config to run ogre 1.x tests in ign-sensors6 on macOS

tutorials/custom_sensors.md
Caught a typo while reading the tutorial. Literally just this change: "It's implement" -> "It's possible to implement"
=> Trivial tutorial typo correction

test/integration/gpu_lidar_sensor.cc
related to #157 
gpu_lidar_sensor integration tests started failing after we switched the default render engine to ogre 1.x. Disabling them for now to get green homebew CI builds.
=> Disable GPU lidar tests on macOS

src/RenderingSensor.cc, test/integration/camera.cc
related to https://github.com/ignitionrobotics/ign-gazebo/pull/1170
Currently when a rendering sensor is removed, the objects in ign-rendering are not destroyed. This PR adds calls to destroy the rendering sensors. Otherwise when a new sensor is created with the same name, ign-rendering will complain that the sensor already exists.
=> Destroy rendering sensors when sensor is removed

CMakeLists.txt, Changelog.md
Preparation for 6.1.0 release.
Comparison to 6.1.0: https://github.com/ignitionrobotics/ign-sensors/compare/ignition-sensors6_6.0.0...ign-sensors6
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/1170
=> Prepare for 6.0.1 release

src/ImuSensor.cc, src/ImuSensor_TEST.cc
Signed-off-by: Aditya <aditya050995@gmail.com>
Closes https://github.com/ignitionrobotics/ign-sensors/issues/174
According to REP 145, an IMU can report orientation with respect to the world, or some given reference frame. The method SetOrientationReference enables this, but this cannot be set via sdf currently.
The ``orientation_reference_frame`` tag ( http://sdformat.org/spec?ver=1.9&elem=sensor#imu_orientation_reference_frame) exposes this, but it is ignored currently in the ``Load`` method for the IMU sensor. This PR aims to set reference orientation when the ``localization`` tag is set to ``CUSTOM`` and ``custom_rpy`` is set to some non zero angles. 
I've added a test case, but if one wants to run it independently, you can use the following sdf …
=> IMU ``custom_rpy``  tag parsing added

Migration.md, src/GpuLidarSensor.cc, test/integration/gpu_lidar_sensor.cc
Fixes #179 
Currently, when filling pointcloud message, the is_dense field is always set to true. According to the definition used by [PCL](https://pointclouds.org/documentation/singletonpcl_1_1_point_cloud.html#a3ca88d8ebf6f4f35acbc31cdfb38aa94), a pointcloud should be considered dense if all point are valid  (i.e. not NaN nor +/-INF). Please refer to the linked issue to understand the common problem that this can cause when using PCL lib.
=> Added Logic to flag pointcloud if invalid point is Detected

include/ignition/sensors/AirPressureSensor.hh, include/ignition/sensors/AltimeterSensor.hh, include/ignition/sensors/CameraSensor.hh, include/ignition/sensors/ForceTorqueSensor.hh, include/ignition/sensors/ImuSensor.hh, include/ignition/sensors/LogicalCameraSensor.hh, include/ignition/sensors/MagnetometerSensor.hh, test/integration/air_pressure.cc, test/integration/altimeter.cc, test/integration/force_torque.cc, test/integration/imu.cc, test/integration/logical_camera.cc, test/integration/magnetometer.cc
* Related to https://github.com/ignitionrobotics/ign-gazebo/pull/1282
Ignition Gazebo calls update directly on non-rendering sensors, but it's easy to call the "wrong" function if one is not careful. There are 2 `Update` functions on the base class:
1. `public: bool Update(const std::chrono::steady_clock::duration &_now, const bool _force);`
1. `public: virtual bool Update(const std::chrono::steady_clock::duration &_now) = 0;`
Most (all?) of the time, one would want to call `1.`, which calls `2.` under the hood and performs extra steps. But since `2.` is also public, and easier to call, we often call `2.` directly by mistake.
This PR solves one of the issues by making it easier to call the base class's function. The test changes in this PR wouldn't be possible without the `using` lines, …
=> Let derived sensors call Sensor::Update

CMakeLists.txt, src/SensorFactory.cc
We've been having CMP0072 policy warnings on Jenkins CI since we upgraded to Focal, see
* https://github.com/ignition-tooling/release-tools/pull/565
* https://github.com/ignitionrobotics/ign-rendering/issues/360
This PR takes the same approach as https://github.com/ignitionrobotics/ign-rendering/pull/528 to silence the CMP0072 warning.
I also tackled this other warning that I see locally with gcc 9.3, but is not coming up on CI yet:
```
/home/chapulina/dev_focal/ws_citadel/src/ign-sensors/src/SensorFactory.cc:140:19: warning: moving a local object in a return statement preve
nts copy elision [-Wpessimizing-move]            
140 |   return std::move(result);                                                                                                         
|          ~~~~~~~~~^~~~~~~~ …
```
=> Fix compiler warnings (CMP0072 and copy elision)

include/ignition/sensors/Sensor.hh, src/Sensor.cc, src/Sensor_TEST.cc
This method allows external uers to set the next update time for a sensor. 
One potential application:
* Sensors that have irregular update times that don't follow a `dt`
This fixes two issues with time and sensors:
* Large jumps forward in time will cause sensors to update too much to "catch up" to the current time, as the next time was only ever incremented by `dt`
* Large jumps backward in time will cause sensors to stop updating until the reach "nextupdatetime"
See the unit tests for intended behaviors.
=> Add API to set next sensor update time

include/ignition/sensors/Sensor.hh, src/AirPressureSensor.cc, src/AltimeterSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/ImuSensor.cc, src/Lidar.cc, src/LogicalCameraSensor.cc, src/MagnetometerSensor.cc, src/RgbdCameraSensor.cc, src/Sensor.cc, src/Sensor_TEST.cc, src/ThermalCameraSensor.cc, test/integration/camera_plugin.cc, test/integration/camera_sensor_builtin.sdf
While I was giving [support for the turtlebot3 in Ignition](https://github.com/ROBOTIS-GIT/turtlebot3_simulations/pull/180) , I found that the `frame_id` is generated with this format `<model_name>::<link_name>::<sensor_bane>`, then when we use the bridge to republish the data in the ROS network, the `frame_id` is modified [here](
https://github.com/ignitionrobotics/ros_ign/blob/8f01ea1dc3767509161d106e62dbb53306b153aa/ros_ign_bridge/src/convert.cpp#L56-L59) and it will look like `<model_name>/<link_name>/<sensor_bane>`, but this format is still not valid, it not matching with any `frame_id` in `tf`. 
This PR overwrite the `frame_id` value and set it to another value which allows to make it compatible with ROS.
I don't know where is the right place to document this.
Following the steps in …
=> Conform to ros format for header field frame_id of sensor msgs

test/integration/air_pressure.cc
Part of https://github.com/ignitionrobotics/ign-math/issues/60
The ign-math Pose addition operator is going to be deprecated, so use the multiplication operator instead. It works in the opposite order, matching the behavior of coordinate transform multiplication. The deprecation is planned for ignition-math7, which will not affect Fortress, but I've targeted this branch to reduce the chance of conflicts when merging forward.
=> Use pose multiplication instead of addition

include/ignition/sensors/ImuSensor.hh, src/ImuSensor.cc, src/ImuSensor_TEST.cc
As per the discussion here : https://github.com/ignitionrobotics/ign-sensors/pull/178#discussion_r780604658, this PR aims to expose ``SetWorldFrameOrientation`` API which accepts heading offset and world frame orientation (``ENU`` by default). If the ``<localization>`` tag for IMU sensor is set to any named frame (https://github.com/ignitionrobotics/sdformat/blob/6404afdf959982f759526dea8700037b50fa7758/sdf/1.9/imu.sdf#L7-L30), the sensor should output its orientation with respect to the frame specified in the ``<localization>`` tag.
There would be another follow up PR in IMU sensor system to use this API
Added some test cases to ``ImuSensor_TEST.cc``
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the …
=> IMU sensor API to get world ref frame and heading offset 

include/ignition/sensors/Sensor.hh, src/Sensor.cc, src/Sensor_TEST.cc, test/integration/TransportTestTools.hh, test/integration/camera.cc
Added `SetActive` and `IsActive` function for enabling and disabling a sensor.
The sensor is active by default. A disabled / non-active sensor will not generate or publish data when the `Update` function is called. It will however update if the `force` argument is true, similar to the behavior in [gazebo-classic](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/sensors/Sensor.cc#L237). 
Run the `INTEGRATION_camera` test.
=> Add function for enabling / disabling a sensor

CMakeLists.txt, include/ignition/sensors/BrownDistortionModel.hh, include/ignition/sensors/Distortion.hh, include/ignition/sensors/ImageBrownDistortionModel.hh, include/ignition/sensors/ImageDistortion.hh, include/ignition/sensors/Sensor.hh, include/ignition/sensors/SensorTypes.hh, src/BrownDistortionModel.cc, src/CMakeLists.txt, src/CameraSensor.cc, src/Distortion.cc, src/ImageBrownDistortionModel.cc, src/ImageDistortion.cc, test/integration/CMakeLists.txt, test/integration/distortion_camera.cc, test/sdf/distortion_camera_sensor_builtin.sdf
Camera distortion has already been implemented in ign-rendering, but in order to use it with ign-gazebo, it must be implemented within ign-sensors.
Distortion is implemented with abstraction (just like how noise is implemented) in  the case that different distortion models are to be implemented. The abstract implementation in ign-sensors would reduce future work for adding additional distortions.
Comments with the `TODO` tag have been added in areas where additional work is required in other repositories to maintain the abstraction. For example, sdf::Distortion does not exist so sdf::Camera is being used instead with it's distortion  element that is hard-coded with the Brown's distortion model coefficients.
Requires the branch: https://github.com/WilliamLewww/ign-gazebo/tree/wlew/distortio …
=> Distortion Camera Sensor

CMakeLists.txt, Changelog.md
Preparation for 6.2.0 release.
Comparison to 6.1.0: https://github.com/ignitionrobotics/ign-sensors/compare/ignition-sensors6_6.1.0...prep_6.2.0
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/1385
=> Prepare for ign-sensors 6.2.0

.github/workflows/ci.yml, include/ignition/sensors/ImuSensor.hh, include/ignition/sensors/Sensor.hh, src/AirPressureSensor.cc, src/AltimeterSensor.cc, src/CMakeLists.txt, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/ImuSensor.cc, src/ImuSensor_TEST.cc, src/Lidar.cc, src/LogicalCameraSensor.cc, src/MagnetometerSensor.cc, src/RgbdCameraSensor.cc, src/Sensor.cc, src/Sensor_TEST.cc, src/ThermalCameraSensor.cc, test/integration/TransportTestTools.hh, test/integration/air_pressure.cc, test/integration/camera.cc, test/sdf/camera_sensor_builtin.sdf
Port ign-msgs6 to main
Branch comparison: https://github.com/ignitionrobotics/ign-sensors/compare/main...ign-sensors6
=> Merge 6 -> main

src/ImuSensor.cc, src/ImuSensor_TEST.cc
Signed-off-by: Aditya <aditya050995@gmail.com>
Originally, the ``custom_rpy`` orientation reference frame for IMUs, added here : https://github.com/ignitionrobotics/ign-sensors/pull/186, accepts a ``parent_frame`` w.r.t which the roll, pitch, yaw are applied. If left blank, this should default to the sensor's parent frame (http://sdformat.org/spec?ver=1.9&elem=sensor#custom_rpy_parent_frame), whereas in the current implementation it defaults to world frame. 
It is not possible to support every possible parent fame for now and only the 'world' can be set as the parent frame, due to limitations with sdf parsing. This PR makes ``custom_rpy`` only accept ``world`` as a parent frame, and anything else is rejected for now. Check this for the original discussion : …
=> custom_rpy parent_frame should be set to 'world' in IMUs

src/ForceTorqueSensor.cc, src/GpuLidarSensor.cc, src/SegmentationCameraSensor.cc
Fixes https://github.com/ignitionrobotics/ign-sensors/issues/217
Additionally it seems that frame_id was not also applied for ForceTorqueSensor and SegmentationCameraSensor, so fixed too.
=> Fix <ignition_frame_id> not working for GpuLidarSensor

src/CameraSensor.cc, test/integration/camera.cc, test/sdf/camera_sensor_l8_builtin.sdf
Add support for 8 bit grayscale format: `L_INT8` or `L8`
Run the `camera` integration test.
You can also test with ign-gazebo.
1. Add `<format>L8</format>` to the `sensors_demo.sdf` world [here](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo6/examples/worlds/sensors_demo.sdf#L381)
1. Launch ign-gazebo with the updated world to see that the top left image display now displays grayscale images
=> Add support for single channel 8 bit grayscale image format

src/CameraSensor.cc, test/integration/triggered_camera.cc, test/sdf/triggered_camera_sensor_builtin.sdf
Starts to fix a broken test for triggered cameras
A test for triggered cameras was added in #194, but it has a few issues.
* It's gtest class name is a duplicate of that from `test/integration/camera.cc`, so change it to `TriggeredCameraTest`
* The test was also being skipped on Ubuntu (which uses ogre2 for testing) due to an irrelevant requirement related to segmentation camera sensors.
* 
=> [fortress] Fix triggered camera test

include/ignition/sensors/Lidar.hh, src/GpuLidarSensor.cc, src/Lidar.cc, src/Lidar_TEST.cc
Depends on:
* https://github.com/gazebosim/sdformat/pull/1015
* https://github.com/gazebosim/gz-rendering/pull/625
Extends GpuLidarSensor to read the new `<visibility_mask>` SDF element introduced in https://github.com/gazebosim/sdformat/pull/1015 and sets it to the ign-rendernig GpuRays object.
Here is an example ign-gazebo world thats show a lidar with visibility mask set. The lidar sees only 2 boxes out of 3. The one that is invisible to the lidar has visibility flags set to value that evaluates to non-zero when bitwise AND'd with the lidar's visbility mask. The smoke is there to test and verify that particle system still affects the lidar readings
<details><summary>lidar_visibility_mask.sdf</summary>
```xml
<?xml version="1.0" ?>
<sdf …
```
=> Sets lidar visibility mask

include/gz/sensors/SegmentationCameraSensor.hh
This was removed in https://github.com/gazebosim/gz-common/pull/350 , and is deprecated/dangling/no longer needed (:
=> Remove deprecated common/PluginMacros.hh include

src/LogicalCameraSensor.cc, test/integration/logical_camera.cc
Part of [gz-math#60](https://github.com/gazebosim/gz-math/issues/60).
As noted in [gz-math#60](https://github.com/gazebosim/gz-math/issues/60), there are concerns about the pose subtraction operator. Given that it is equivalent to multiplying by an inverse (albeit with reversed order), the subtraction operator will be deprecated. This PR replaces usage of the soon-to-be-deprecated operator with the equivalent multiplication by inverse.
Build against https://github.com/gazebosim/gz-math/pull/438 and confirm that tests still pass and that there are no deprecation warnings.
=> Use pose multiplication instead of subtraction

CMakeLists.txt, include/gz/sensors/CMakeLists.txt, src/CMakeLists.txt, test/integration/CMakeLists.txt, test/performance/CMakeLists.txt, test/regression/CMakeLists.txt
* Part of https://github.com/gazebo-tooling/release-tools/issues/719
=> [ign -> gz] CMake functions

test/integration/thermal_camera.cc
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
Disabling a faling test on MacOS, I think it's closely related to same error described here: https://github.com/gazebosim/gz-rendering/issues/654. I think it's better to track both issues together, I can open a new issue if it's preferred for this test.
Should fix remaining test regression on MacOS + Fortress buildfarm jobs.
Reference, see: https://build.osrfoundation.org/job/ignition_sensors-ci-ign-sensors6-homebrew-amd64/25/
FYI: @Crola1702
=> Disable thermal camera test on MacOS

CMakeLists.txt, Changelog.md, api.md.in, include/ignition/sensors/config.hh.in, test/integration/all_symbols_have_version.bash.in, tutorials.md.in
Port `ign-sensors3 ` ➡️  `ign-sensors6`
Branch comparision: https://github.com/ignitionrobotics/ign-sensors/compare/ign-sensors6...ign-sensors3
=> Merge ign-sensors3 ➡️  ign-sensors6

src/CMakeLists.txt
* Follow up to https://github.com/gazebosim/gz-sensors/pull/247
Missed an `ign`
=> Fix forward-port: use gz_add_component

src/CMakeLists.txt
Fixes homebrew build of ign-gazebo3 https://github.com/osrf/homebrew-simulation/pull/2008, alternative to https://github.com/gazebosim/gz-sim/pull/1663
The ign-gazebo3 builds have been failing since ign-sensors 3.4.0 was released (see https://github.com/osrf/homebrew-simulation/pull/2008#issuecomment-1228761373).
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-ign-gazebo3-homebrew-amd64&build=246)](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/246/) https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/246/
From the cmake output:
~~~
-- Searching for dependencies of ignition-sensors3-gpu_lidar
...
Found package configuration file: …
=> Add missing DEPENDS_ON_COMPONENTS parameters

examples/custom_sensor/Odometer.cc, include/gz/sensors/CameraSensor.hh, include/gz/sensors/DepthCameraSensor.hh, include/gz/sensors/LogicalCameraSensor.hh, include/gz/sensors/SegmentationCameraSensor.hh, include/gz/sensors/ThermalCameraSensor.hh, include/gz/sensors/WideAngleCameraSensor.hh, src/BoundingBoxCameraSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/ImuSensor_TEST.cc, src/Lidar_TEST.cc, src/LogicalCameraSensor.cc, src/RgbdCameraSensor.cc, src/SegmentationCameraSensor.cc, src/ThermalCameraSensor.cc, src/WideAngleCameraSensor.cc, test/integration/camera.cc, test/integration/depth_camera.cc, test/integration/distortion_camera.cc, test/integration/gpu_lidar_sensor.cc, test/integration/logical_camera.cc, test/integration/rgbd_camera.cc, test/integration/segmentation_camera.cc, test/integration/thermal_camera.cc, test/integration/triggered_camera.cc, test/integration/wide_angle_camera.cc
Required by
* https://github.com/gazebosim/gz-transport/pull/315
* https://github.com/gazebosim/gz-sim/pull/1566
Include the narrowest headers for faster compilation.
=> Fix msgs.hh uses

include/gz/sensors/WideAngleCameraSensor.hh, src/WideAngleCameraSensor.cc, test/integration/wide_angle_camera.cc
This fixes the `INTEGRATION_wide_angle_camera` test for me locally on macOS. For some reason, we have to remove the sensor and scene visuals manually in this test otherwise it segfaults on macOS while cleaning up shared pointers. This does not happen on Ubuntu.
Related PR: https://github.com/gazebosim/gz-rendering/pull/718
=> Clear scene before exiting wide_angle_camera_test

tutorials/segmentation_camera.md
updated a broken link to point to a wikipedia page instead.
=> Fix link in segmentation camera tutorial

CMakeLists.txt, Changelog.md
Preparation for 7.0.0 release.
Comparison to 6.6.0: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors6_6.6.0...changelog_7
=> Update Changelog for 7.0.0

CMakeLists.txt, src/CameraSensor.cc, src/RgbdCameraSensor.cc
Closes #175 
This adds the ability for a `CameraSensor` or `RgbdCameraSensor` to use the optional sdf specified `optical frame_id` that will be used when publishing the camera_info, rgb_image, and point_cloud topic's from a simulated sensor.  Note: this PR depends on an open [PR in sdformat](https://github.com/gazebosim/sdformat/pull/1109).
This feature request was noted in [CameraSensors.cc](https://github.com/gazebosim/gz-sensors/blob/ign-sensors6/src/CameraSensor.cc#L677-L680) and will help close https://github.com/ignitionrobotics/ign-sensors/issues/175 in ign-sensors.
Here are the instructions on how I setup my test environment:
- I started with the following Docker image from Open Robotics. `osrf/ros:humble-desktop`
- Clone an [example …
=> Add optional optical frame id to camera sensors

src/CameraSensor.cc, test/integration/camera.cc, test/sdf/camera_sensor_l16_builtin.sdf
Closes https://github.com/gazebosim/gz-sensors/issues/275
Add check for 16 bit image format. This should already be supported at the gz-rendering library. It's just a matter of enabling it in gz-sensors.
You can also test with `sensors_demo.sdf` world. Change one of the cameras to output 16 bit images by adding `<format>L_INT16</format>` [here](https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/examples/worlds/sensors_demo.sdf#L382). You should grayscale images in the top left Image Display GUI plugin
Run `INTEGRATION_camera` test
=> Add support for 16 bit image format

src/AirPressureSensor.cc, src/AltimeterSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/GpuLidarSensor.cc, src/ImageGaussianNoiseModel.cc, src/ImuSensor.cc, src/ImuSensor_TEST.cc, src/Lidar.cc, src/Lidar_TEST.cc, src/LogicalCameraSensor.cc, src/MagnetometerSensor.cc, src/PointCloudUtil.hh, src/RenderingSensor.cc, src/RgbdCameraSensor.cc, src/Sensor_TEST.cc, src/ThermalCameraSensor.cc
Clean up Windows warnings
- ~~Added tests~~
- ~~Updated documentation (as needed)~~
- ~~Updated migration guide (as needed)~~
- ~~Consider updating Python bindings (if the library has them)~~
=> Fix Windows warnings

src/AirPressureSensor.cc, src/AltimeterSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/GpuLidarSensor.cc, src/ImageGaussianNoiseModel.cc, src/ImuSensor.cc, src/ImuSensor_TEST.cc, src/Lidar.cc, src/Lidar_TEST.cc, src/LogicalCameraSensor.cc, src/MagnetometerSensor.cc, src/PointCloudUtil.hh, src/RenderingSensor.cc, src/RgbdCameraSensor.cc, src/Sensor_TEST.cc, src/ThermalCameraSensor.cc
=> Improved coverage Lidar

src/Noise_TEST.cc
=> Improved noise coverage

src/RgbdCameraSensor.cc
Follow-up to #277
Ensure that `image.pb.h` is included even when `_MSC_VER` is not defined.
=> RgbdCameraSensor.cc: fix include

CMakeLists.txt
Preparation for 3.5.0 prerelease.
Comparison to 3.4.0: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors3_3.4.0...ign-sensors3
Needed by [<PR(s)>](https://github.com/gazebosim/gz-sim/pull/1646)
=> 3.5.0 pre1

src/Sensor_TEST.cc
Signed-off-by: Aditya <aditya050995@gmail.com>
This PR fixes a compile time warning in ``Sensors_TEST.cc`` due to ign- > gz renaming.
=> Fix compile time warning in Sensors_TEST

src/NavSatSensor.cc
Signed-off-by: quentinGllmt <quentin.guillemot@free.fr>
Related to https://github.com/gazebosim/gz-sensors/pull/295
Applied `<ignition_frame_id>` tag
=> [backport Fortress] Fix navsat frame id (#295)

src/Sensor.cc, src/Sensor_TEST.cc, test/integration/triggered_camera.cc, test/sdf/camera_intrinsics.sdf, test/sdf/camera_sensor_builtin.sdf, test/sdf/camera_sensor_l16_builtin.sdf, test/sdf/camera_sensor_l8_l16_builtin.sdf
Signed-off-by: Alejandro Hernández Cordero <ahcorde@gmail.com>
Renamed `ignition_frame_id` to `gz_frame_id` and fix warning
=> Renamed ignition_frame_id to gz_frame_id and fix warning

CMakeLists.txt, include/gz/sensors/DopplerVelocityLog.hh, include/gz/sensors/EnvironmentalData.hh, src/CMakeLists.txt, src/DopplerVelocityLog.cc, src/EnvironmentalData.cc, test/integration/CMakeLists.txt, test/integration/dvl.cc
This patch adds a DVL sensor, implemented as a custom rendering sensor. Needs https://github.com/gazebosim/gz-msgs/pull/317.
TBD
=> Add DopplerVelocityLog sensor

src/CameraSensor.cc, test/integration/camera.cc, test/sdf/camera_intrinsics.sdf
Closes https://github.com/gazebosim/gz-sensors/issues/288
This PR extends the camera sensor functionality to support custom projection matrix based on input instrinics values. Specifically, it reads the lens `<instrinsics>` params from SDF, builds the projection matrix from the input values using [code ported from Gazebo-classic](https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/rendering/Camera.cc#L240-L253), and set the camera to use this custom projection matrix.
Expanded the camera intrinsics integration test to compare image output from cameras with different intrinsics values.
=> Set custom projection matrix based on intrinsics params from SDF

test/integration/camera.cc, test/integration/depth_camera.cc, test/integration/distortion_camera.cc, test/integration/gpu_lidar_sensor.cc, test/integration/rgbd_camera.cc, test/integration/thermal_camera.cc, test/integration/triggered_camera.cc, test/integration/wide_angle_camera.cc
Toward #284
Ogre tests are not working on windows as discussed in #284. 
=> Disable ogre tests on windows

CMakeLists.txt, include/gz/sensors/AirSpeedSensor.hh, include/gz/sensors/SensorTypes.hh, src/AirSpeedSensor.cc, src/CMakeLists.txt, test/integration/CMakeLists.txt, test/integration/air_speed.cc
Signed-off-by: Alejandro Hernández Cordero <ahcorde@gmail.com>
Added air speed sensor
Depends on:
- https://github.com/gazebosim/sdformat/pull/1215
- https://github.com/gazebosim/gz-msgs/pull/321
=> Added airspeed sensor

CMakeLists.txt, Changelog.md
Preparation for 6.7.0 prerelease.
Comparison to 6.6.0: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors6_6.6.0...ign-sensors6
Needed by upcoming gui and sim forward ports
=> 6.7.0 prerelease

.github/ci/packages.apt, CMakeLists.txt, tutorials/thermal_camera.md
Bumping to use the new msgs and transport versions in Harmonic, msgs10 and transport13
https://github.com/gazebo-tooling/release-tools/issues/878
=> Bump msgs and transport version in Harmonic

src/RenderingSensor.cc, test/integration/boundingbox_camera.cc, test/integration/depth_camera.cc, test/integration/gpu_lidar_sensor.cc, test/integration/rgbd_camera.cc, test/integration/segmentation_camera.cc, test/integration/thermal_camera.cc
Rendering tests have been failing on Jammy github actions for a while. This PR fixes the tests and we should now get a green CI.
It was found that all rendering tests segfault on exit, caused by destructor of rendering objects. The changes in this PR fix the test by cleaning up these pointers. Side note: tests are only failing on Jammy github actions and not on other platforms. I'm also not able to reproduce the failing tests locally. Fixes should also be done on the gz-rendering side to make sure objects can destroyed safely when going out of scope.
=> Fix rendering tests on Jammy

include/gz/sensors/BoundingBoxCameraSensor.hh, include/gz/sensors/CameraSensor.hh, src/BoundingBoxCameraSensor.cc, src/CameraSensor.cc, test/integration/CMakeLists.txt, test/integration/triggered_boundingbox_camera.cc, test/sdf/triggered_boundingbox_camera_sensor_builtin.sdf
Signed-off-by: Valentina Vasco <vale88.vasco@gmail.com>
Closes #321
This adds the possibility to trigger a BoundingBoxCamera.
Checkout the branch https://github.com/vvasco/gz-sensors/tree/triggered_bounding_box_camera and run the `INTEGRATION_triggered_boundingbox_camera`
=> Added trigger to BoundingBoxCamera

src/Camera_TEST.cc
Fix incorrect camera info sdf tag used in test
=> Fix Camera info test

src/BoundingBoxCameraSensor.cc, test/integration/triggered_boundingbox_camera.cc
Fixes #328
Fixes flaky bounding box camera test due to timing / race condition. This PR fixes the test by making sure:
1. we allow time for trigger msg to arrive to bounding box camera
2. make sure msgs are received on the box topic (instead of image topic) which is what the tests is checking
3. add mutex to protect the `isTriggered` variable.
=> Fix flaky  bounding box camera test

src/CameraSensor.cc
Add a call to make sure we destroy the rendering camera object in destructor
=> Cleanup resources in CameraSensor destructor

src/BoundingBoxCameraSensor.cc, src/CameraSensor.cc, test/integration/triggered_boundingbox_camera.cc, test/integration/triggered_camera.cc, test/sdf/triggered_boundingbox_camera_sensor_topic_builtin.sdf, test/sdf/triggered_camera_sensor_topic_builtin.sdf
Currently the sensor manager will fail to create a triggered camera sensor if the `<trigger_topic>` is unspecified / empty, the sensor. This PR fixes the problem by generating a default value for the `<trigger_topic>` if it's empty.
You can test with the `triggered_camera_sensor.sdf` world in gazebo. Comment out the [<trigger_topic>](https://github.com/gazebosim/gz-sim/blob/gz-sim7/examples/worlds/triggered_camera_sensor.sdf#L296) line in the world sdf file and launch gz sim:
```sh
gz sim -v 4 triggered_camera_sensor.sdf
``` 
Before the changes in this PR, you'll get these error msgs:
```sh
[Err] [CameraSensor.cc:461] Invalid trigger topic name
[Err] [SensorFactory.hh:105] Failed to load sensor [camera::link::camera] of type[camera]
[Err] [Manager.hh:80] Failed to create sensor.
[Err] …
```
=> Generate default trigger topic name if empty

test/integration/triggered_camera.cc
Fixes https://github.com/gazebosim/gz-sensors/issues/345
Test fails because the sensor tries to process the trigger message before it actually receives the message.
The fix is to wait (sleep) a couple of seconds before processing the message. The [same logic is done](https://github.com/gazebosim/gz-sensors/blob/82f0e448b507c740dce499d9b4ed44b8f80151e3/test/integration/triggered_camera.cc#L134-L135) in the other triggered camera test.
=> Fix flaky triggered camera test

include/gz/sensors/DepthCameraSensor.hh, src/CameraSensor.cc, src/GpuLidarSensor.cc, src/NavSatSensor.cc, src/SegmentationCameraSensor.cc, src/Sensor.cc
- Change remaining ignerr to gzerr
- Add one missing header
- Ensure parameter names match in function declaration and definition
=> Minor cleanup

CMakeLists.txt
GzProtobuf: Do not require version 3 do support Protobuf 4.23.2 (23.2)
The motivation is similar to https://github.com/gazebosim/gz-msgs/pull/346 . For some reason in the case of this library there are no linking problem at build time, but rather runtime ABI issues: https://github.com/conda-forge/gz-sensors-feedstock/pull/13#issuecomment-1579408286 .
Install protobuf 23.2 and run the tests (I guess the only way to do it easily for now is to use conda-forge, see https://repology.org/project/protobuf/versions .
=> Fix finding GzProtobuf to support version 4.23.2

CMakeLists.txt
Backport #351 to fix finding the newest versions of protobuf, which is now in homebrew-core. Use rebase-and-merge.
=> Backport #351: Support protobuf >= 22

src/CameraSensor.cc
I was try to use the `example/save_image` which segfaults during execution. In the CameraSensor it was failing to check if the sensor element was not null before accessing it.
=> Fix CameraSensor to check if element is null before access

.github/workflows/ci.yml, CMakeLists.txt, include/gz/sensors/AirPressureSensor.hh, include/gz/sensors/AltimeterSensor.hh, include/gz/sensors/DepthCameraSensor.hh, include/gz/sensors/ForceTorqueSensor.hh, include/gz/sensors/ImuSensor.hh, include/gz/sensors/Lidar.hh, include/gz/sensors/Manager.hh, include/gz/sensors/Sensor.hh, include/gz/sensors/SensorTypes.hh, include/gz/sensors/ThermalCameraSensor.hh, include/gz/sensors/WideAngleCameraSensor.hh
Harmonic only supports Jammy so removing Focal CI.
=> Disable Focal on Harmonic

include/gz/sensors/CameraSensor.hh, src/CameraSensor.cc, src/DepthCameraSensor.cc
I was using DepthCameraSensor along with the ros_gz_bridge and noticed that the point cloud could not be visualized in rviz because the optical frame was not being assigned to the message being produced by this package.
=> Expose optical frame in CameraSensor to be used by DepthCameraSensor

src/AirSpeedSensor.cc, test/integration/air_speed.cc
Required https://github.com/gazebosim/gz-msgs/pull/365
Added `air_speed.proto` msgs. I was using `air_speed_sensor.proto` in older version to avoid breaking ABI, in `main` we can do things properly
=> Update air sensor with air_speed.proto

src/BoundingBoxCameraSensor.cc, test/integration/air_pressure.cc, test/integration/air_speed.cc, test/integration/altimeter.cc, test/integration/boundingbox_camera.cc, test/integration/camera.cc, test/integration/dvl.cc, test/integration/force_torque.cc, test/integration/imu.cc, test/integration/magnetometer.cc, test/integration/navsat.cc, test/integration/segmentation_camera.cc, test/integration/triggered_boundingbox_camera.cc, test/integration/wide_angle_camera.cc
Many sensor tests didn't actually include the headers that they were using.  This breaks with the new message generation (we are probably transitively including less).
=> Tests need to include message types they are using

src/ImuSensor.cc
This PR fills the imu covariance field
This PR depends on this one: https://github.com/gazebosim/gz-msgs/pull/333
The published imu message is missing the covariance fields for linear_acceleration, angular_velocity and orientation_covariance. Those can be very useful when bridging between gz and ros.
Note: a Pr on ros_gz to update the convertion to ros is coming
=> populate the covariance fields using the noise models

tutorials/install.md
https://github.com/gazebosim/gazebo_test_cases/issues/179
ign/ignition -> gz
=> Replace ign with gz in installation tutorial

.github/workflows/triage.yml, Changelog.md, include/gz/sensors/CameraSensor.hh, src/CameraSensor.cc, src/DepthCameraSensor.cc
Port gz-sensors7 to gz-sensors8
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/gz-sensors8...gz-sensors7
=> Merge 7 -> 8

src/CameraSensor.cc, test/integration/camera.cc, test/sdf/camera_intrinsics.sdf, test/sdf/camera_projection.sdf
In Garden some PR were included to fix the camera topic info. This PR backport some of the relevant PRs
=> [backport fortress] camera info topic published with the right data

.github/workflows/triage.yml, CMakeLists.txt, Changelog.md, README.md, include/gz/sensors/CameraSensor.hh, src/CameraSensor.cc, src/DepthCameraSensor.cc, tutorials/install.md, tutorials/intro.md, tutorials/thermal_camera.md
Port gz-sensors8 to main
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/main...gz-sensors8
=> Merge: 8 -> main

src/RenderingSensor.cc, test/integration/camera_plugin.cc, test/integration/depth_camera_plugin.cc, test/integration/gpu_lidar_sensor_plugin.cc, test/integration/rgbd_camera_plugin.cc, test/integration/thermal_camera_plugin.cc
Fixes #393.
Backports #169, and #324 to citadel to fix rendering tests
**Note to maintainers**: Remember to use **Rebase-and-Merge**.
=> Backport rendering test fixes from fortress to citadel

.github/ci/packages.apt, .github/disabled_workflows/macos.yml, CMakeLists.txt, examples/custom_sensor/CMakeLists.txt, examples/save_image/CMakeLists.txt, tutorials/thermal_camera.md
See https://github.com/gazebo-tooling/release-tools/issues/1027
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-sensors9

src/GaussianNoiseModel.cc
Fixes #395 
The fix checks for zero standard deviation before sampling the normal distribution. If the standard deviation is zero, the mean is set directly. I've fixed both cases as mentioned in #395, as I think a crash is undesirable for both cases, but perhaps a warning should be emitted in Load() if the state standard deviation is zero.
=> GaussianNoiseModel: avoid calling DblNormal with invalid standard deviation

CMakeLists.txt, src/PointCloudUtil.hh
Part of the works to enable visibility hidden by default https://github.com/gazebosim/gz-cmake/pull/392. Part of https://github.com/gazebosim/gz-cmake/issues/166
The PR replaces a custom visibility method by the macro provided by gz-cmake.
=> Use GZ_ visibilty macro instead of custom _EXPORTS_API

README.md
Updated to point to `gz-sensors8` instead of `main` jobs
=> Update CI badges to point to release branch job

CMakeLists.txt, Changelog.md
Preparation for 3.6.0 release.
Comparison to <x.y.z>: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors3_3.5.0...prep_3.6.0
=> Prepare for 3.6.0 release

src/Sensor.cc, src/Sensor_TEST.cc
This is meant to help migration to newer versions of Gazebo and allows users to replace ignition_frame_id in their SDF files while still in Fortress.
See https://github.com/ros-planning/navigation2/pull/3634#discussion_r1443279660 for more context
`./UNIT_Sensor_TEST`
=> Allow specifying gz_frame_id as an alternative to ignition_frame_id

CMakeLists.txt, Changelog.md
Preparation for 6.8.0 release.
Comparison to 6.7.1: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors6_6.7.1...ign-sensors6
Needed by https://github.com/ros-planning/navigation2/pull/3634#discussion_r1443279660
=> Prepare for 6.8.0 Release

src/DepthCameraSensor.cc, src/RgbdCameraSensor.cc
Related pull request: https://github.com/gazebosim/gz-rendering/pull/965
* Updated DepthCameraSensor and RGBDCameraSensor to connect to the point cloud connection only when there is a subscriber. 
To be used together with https://github.com/gazebosim/gz-rendering/pull/965
Here are the results showing the time taken to perform a [Render()](https://github.com/gazebosim/gz-rendering/blob/7116f01bd5e015cbfc245e55641d8b5fed99f586/ogre2/src/Ogre2DepthCamera.cc#L971) operation by the depth camera in gz-rendering before and after the changes.
* blue line (before) - render time taken is consistent regardless of whether you subscribe to depth or point cloud data.
* red line (after) - I first subscribed to get depth data. After approx 120 iterations, I switched to get rgb point cloud data and you …
=> DepthCamera and RGBDCamera - optimize RGB point cloud connection

src/DepthCameraSensor.cc, src/GpuLidarSensor.cc
Fixes bug from the https://github.com/gazebosim/gz-sensors/pull/195#issuecomment-1719254639
In Gazebo Fortress, pointclouds were still using `Name` to set `frame_id`, making it impossible to overwrite to anything visible by ROS.
=> Fix frames set to Name instead of FrameId for pointclouds

.github/workflows/ci.yml, .github/workflows/triage.yml, Changelog.md, README.md, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/RgbdCameraSensor.cc, src/Sensor_TEST.cc, test/integration/camera.cc
Port gz-sensors8 to main
Branch comparison: https://github.com/gazebosim/gz-sensors/compare/main...gz-sensors8
=> Merge 8 -> main

src/GaussianNoiseModel.cc
Fixes https://github.com/gazebosim/gz-sensors/issues/395
Backport of the following fix:
The fix checks for zero standard deviation before sampling the normal distribution. If the standard deviation is zero, the mean is set directly. I've fixed both cases as mentioned in https://github.com/gazebosim/gz-sensors/issues/395, as I think a crash is undesirable for both cases, but perhaps a warning should be emitted in Load() if the state standard deviation is zero.
**Note to maintainers**: Remember to use **Rebase-and-Merge**
=> [backport harmonic] Avoid calling DblNormal with invalid standard deviation (#396)

src/DopplerVelocityLog.cc
Supresses warning shown in gz-sensors main jobs on jammy.
https://build.osrfoundation.org/job/gz_sensors-ci-main-jammy-amd64/59/gcc/
The variable is marked as unused by gcc, because it's only used in an assert condition. This will put an extra void statement so the compiler gets the warning suppressed.
=> Suppress unused variable warning

src/BoundingBoxCameraSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/GpuLidarSensor.cc, src/RgbdCameraSensor.cc, src/SegmentationCameraSensor.cc, src/ThermalCameraSensor.cc, src/WideAngleCameraSensor.cc
Related PR: https://github.com/gazebosim/gz-sim/pull/2425
When most of the rendering sensors are created, I realized that we do not actually set the pose of the internal rendering sensor objects anywhere in gz-sensors. Instead we currently rely on gz-sim to update these poses on every iteration. This PR now sets the sensor pose on creation. It removes pose updates in relevant `Update` functions if any. ~~Additionally for camera based sensors, the final pose of the camera sensor is the combined result of both `//sensor/pose` and `//sensor/camera/pose`.~~ **Update**: No longer setting final pose to take into account `//sensor/camera/pose`, see https://github.com/gazebosim/gz-sim/pull/2433#issuecomment-2150894010 - planning to deprecate / remove this tag. 
**Note to maintainers**: Remember …
=> Set rendering sensor pose

include/gz/sensors/Sensor.hh, src/Sensor.cc, src/Sensor_TEST.cc
Added `Sensor::IsTriggered` function.
=> Add API to check if sensor is in trigger mode

src/BoundingBoxCameraSensor.cc
Fixes #440
test was broken by #432. The call to `UpdateLensIntrinsicsAndProjection` makes changes to camera sdf which causes the second call to think that the bounding box camera needs to use a custom projection matrix. So the fix is to use a copy for the first call instead.
=> Fix boundingbox_camera integration test

src/CameraSensor.cc, src/DopplerVelocityLog.cc, src/GpuLidarSensor.cc, src/RgbdCameraSensor.cc, src/Sensor.cc, src/Sensor_TEST.cc, test/integration/dvl.cc, test/integration/gpu_lidar_sensor.cc, test/sdf/camera_intrinsics.sdf, test/sdf/camera_projection.sdf, test/sdf/camera_sensor_builtin.sdf, test/sdf/camera_sensor_l16_builtin.sdf, test/sdf/camera_sensor_l8_l16_builtin.sdf, test/sdf/depth_camera_intrinsics.sdf
Related issue: https://github.com/gazebosim/gz-sensors/issues/306
Depends on: https://github.com/gazebosim/sdformat/pull/1454
The different ways of specifying sensor frame id are being deprecated. This PR makes use of the new //sensor/frame_id sdf element introduced in https://github.com/gazebosim/sdformat/pull/1454. It also deprecates the use of the custom `<gz_frame_id>` tag. If both tags exist, `<frame_id>` will override `<gz_frame_id>`
All test files have been updated to use `<frame_id>` instead of `<gz_frame_id>` and the affected integration tests should pass, e.g. depth, thermal, rgbd camera integration tests.
=> Use //sensor/frame_id sdf element

src/DopplerVelocityLog.cc, src/GpuLidarSensor.cc, src/Sensor.cc, test/integration/dvl.cc, test/integration/gpu_lidar_sensor.cc
Partial backport of #444. Ported changes that fix missing / incorrect DVL and GpuLidar frame_ids
=> Port frame_id fixes from #444

include/gz/sensors/Lidar.hh, src/Lidar.cc, test/integration/gpu_lidar_sensor.cc
The GpuLidarSensor publishes to 2 topics: 1) lidar scan and 2) points cloud. Previously if the user subscribes to just the point cloud topic, we perform extra computation to pack and publish lidar scans as well. This PR adds an additional check to make sure we don't do extra work when there are not lidar scan subscribers.
In order to make this work, I also had to modify functions for directly accessing lidar scan data. They were accessing the lidar scan msg (which now never gets populated if there are no subscribers), so I modified them to access data from the raw laser buffer instead.
I also fixed the frame id for the lidar scan msg.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` …
=> Publish lidar scan only if there are lidar scan connections

src/CameraSensor.cc, src/DepthCameraSensor.cc, src/Lidar.cc
When Gaussian noise params and distortion coefficients are 0s, there shouldn't be any change to the sensor output. So skip doing extra computations in this case. 
One instance where this usually happens is when a user saves the world to file in gz-sim, all sdf elements are written out with their default values. So when you load the saved world sdf file back in, you now have noise / distortion sdf elements present but with values of 0s.
=> Optimization: skip applying noise and distortion to lidars and camera sensors if parameters are 0s

include/gz/sensors/ForceTorqueSensor.hh, src/ForceTorqueSensor.cc, test/integration/force_torque.cc
Needed for https://github.com/gazebosim/gz-sim/issues/2268 and https://github.com/gazebosim/gz-sim/issues/2391.
Currently the wrench data published by gz-transport is not available via the C++ API. This pull request adds an accessor to the most recent `Wrench` message that is identical to that published on gz-transport.
Build and run `bin/INTEGRATION_force_torque`
=> ForceTorqueSensor: add API for newest measurement

include/gz/sensors/Lidar.hh, src/Lidar.cc, src/Sensor.cc, test/integration/gpu_lidar_sensor.cc
Backport #446 and #447
**Note to maintainers**: Remember to **Rebase and merge** with commit (not squash-merge or merge)
=> Backport lidar optimization and frame fixes

src/DopplerVelocityLog.cc
=> Remove unused variable in DopplerVelocityLog

src/DopplerVelocityLog.cc
Fixes #<NUMBER>
Fixed unused variable warning in DVL.
=> Fixed unused variable warning in DVL

.github/workflows/ci.yml, CMakeLists.txt, README.md, examples/custom_sensor/CMakeLists.txt
Similar to https://github.com/gazebosim/gz-rendering/pull/1037. This PR adds github actions for ubuntu noble and updates min required cmake version.
=> Enable Ubuntu Noble github actions, require cmake 3.22.1

src/RgbdCameraSensor.cc
Fixes [No number]
When using rgbd_camera as sensor, `frame_id` is filled with `FrameId()` (for example `tiago/head_2_link/head_front_camera_frame_sensor`), instead of `OpticalFrameId()` (for example, `head_front_camera_rgb_optical_frame`). So, the `frame_id` in the messages is wrong.
This PR fixes it.
I hope it helps. Any comment is welcome :)
=> Fix frame_id in rgbd_camera

src/DopplerVelocityLog.cc
Fixed deprecation warning by updating the `gz::math::SphericalCoordinate::PositionTransform` call to use the new `gz::math::CoordinateVector3` arg introduced in https://github.com/gazebosim/gz-math/pull/616. 
cc @peci1 
=> Fix SphericalCoordinate deprecation warning in DVL sensor

CMakeLists.txt, Changelog.md
Preparation for 9.0.0~pre1 release.
Comparison to 8.2.0: https://github.com/gazebosim/gz-sensors/compare/gz-sensors8_8.2.0...prep_9.0.0pre1
=> Prepare for 9.0.0~pre1 release

tutorials/custom_sensors.md, tutorials/install.md, tutorials/segmentation_camera.md, tutorials/thermal_camera.md
Update tutorial pages to include a link to the next tutorial. Addresses https://github.com/gazebosim/gazebo_test_cases/issues/1510#issuecomment-2324526093
This is similar to what already exists in [intro.md](https://github.com/gazebosim/gz-sensors/blob/c1abfed3a116e439196ab511657b9d954ea42e2b/tutorials/intro.md?plain=1#L3)
=> Add links to subsequent tutorials

tutorials/segmentation_camera.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1515
Little fixes found when going through the tutorial.
I renamed some topics so that they correspond directly to what is available in `segmentation_camera.sdf` so that users can directly apply what they see in the tutorial.
=> tutorials/segmentation_camera: Little fixes

include/gz/sensors/CameraSensor.hh, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/RgbdCameraSensor.cc
Port `<optical_frame_id>` fixes from https://github.com/gazebosim/gz-sensors/pull/458 and https://github.com/gazebosim/gz-sensors/pull/362 for DepthCamera and RGBD camera sensors.
To test:
Run with this exampel [optical_frame_id.sdf](https://gist.github.com/iche033/a925f9567640fbbdb5b3601bc96013c7) world and check the frame_id field in various topics.
```bash
ign gazebo -v 4 -s -r optical_frame_id.sdf
```
```bash
ign topic -e -t /rgbd/camera_info  | grep -A 2 frame_id
ign topic -e -t /rgbd/image  | grep -A 2 frame_id
ign topic -e -t /rgbd/depth_image  | grep -A 2 frame_id
ign topic -e -t /rgbd/points  | grep -A 2 frame_id
ign topic -e -t /camera_info  | grep -A 2 frame_id
ign topic -e -t /depth/points | grep -A 2 frame_id
ign topic -e -t /depth | grep -A 2 frame_id
```
**Note to …
=> Backport fix for optical_frame_id in Depth and RGBD camera sensors

CMakeLists.txt, Changelog.md
Preparation for 6.8.1 release.
Comparison to 6.8.0: https://github.com/gazebosim/gz-sensors/compare/ignition-sensors6_6.8.0...prep_6.8.1
=> Prepare for 6.8.1 release

src/BoundingBoxCameraSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/RgbdCameraSensor.cc, src/SegmentationCameraSensor.cc, src/ThermalCameraSensor.cc, src/WideAngleCameraSensor.cc
Check to verify that camera sensors have non-zero width / height before creating the rendering cameras. The check prevents gz-sim from crashing and will output a more meaningful msg.
=> Check camera sensors have non-zero width or height

src/WideAngleCameraSensor.cc
Closes https://github.com/gazebosim/gz-sensors/issues/479
Related PR: https://github.com/gazebosim/gz-rendering/pull/1097
Added L8 and L16 type support. 
You'll first need https://github.com/gazebosim/gz-rendering/pull/1097
Then edit [wide_angle_camera.sdf](https://github.com/gazebosim/gz-sim/blob/d83d1352600022ea9da20906000a963580c7f258/examples/worlds/wide_angle_camera.sdf#L308) world in gz-sim, and add `<format>L8</format>` to the `//model/link/sensor/camera/image` tag, e.g.
```diff
diff --git a/examples/worlds/wide_angle_camera.sdf b/examples/worlds/wide_angle_camera.sdf
index 8482ae695..ce9c49c45 100644
--- a/examples/worlds/wide_angle_camera.sdf
+++ b/examples/worlds/wide_angle_camera.sdf
@@ -306,6 +306,7 @@
<image>
<width>800</width>
<height>600</height>
+ …
```
=> Add support for L8 and L16 image formats in WideAngleCameraSensor

include/gz/sensors/LogicalCameraSensor.hh, include/gz/sensors/Sensor.hh, src/LogicalCameraSensor.cc
This PR mainly adds the visualization of Frustum.
We could see it was present in gazebo classic and from gazebo garden onwards the plugin/feature is not available.
$ Build gazebo from source.
$ . install/setup.sh
$ gz sim examples/worlds/visualize_frustum.sdf
1. Play the simulation.
2. Select the topic from scroll down.
3. Refresh it to get the "logical_camera/frustum" topic.
4. Subcriibed to "logical_camera/frustum".
5. Final output
- https://github.com/gazebosim/gz-sim/pull/2707
- https://github.com/gazebosim/gz-rendering/pull/1095
=> Visualze Frustum

examples/custom_sensor/Odometer.cc
Fixes #502 
Replaced calls to GetElement with FindElement in examples
=> Replace calls to Getlement with FindElement in examples

include/gz/sensors/AirSpeedSensor.hh, src/AirSpeedSensor.cc
Result from the discussion in https://github.com/PX4/PX4-Autopilot/pull/24452
Add a new function `SetWindVelocity()` to receive the wind information from the airspeed sensor plugin in gz-sim
=> Fix airspeed calculation under wind influence by wind triangle

.github/workflows/ci.yml, tutorials/boundingbox_camera.md, tutorials/segmentation_camera.md
Related to https://github.com/gazebo-tooling/release-tools/issues/1222, split out from https://github.com/gazebosim/gz-sensors/pull/515
Jammy isn't officially supported for Jetty, so disable it and move special checks to use Noble.
=> ci.yml: use noble, disable jammy

.github/workflows/ci.yml, tutorials/boundingbox_camera.md, tutorials/segmentation_camera.md
Partial backport of #516
Enables doxygen checks on 24.04 and fixes complaints related to heading depth. Also disable redundant checks on Jammy.
=> ci.yml: check doxygen on 24.04

src/CameraSensor.cc
Closes #518
Allows camera sensor HFOV as narrow as 0.5°, and even bellow.
Create a camera sensor which an HFOV of 0.5° (~0.0087 rad) and launch a simulation
Corresponding PR in `sdformat` : https://github.com/gazebosim/sdformat/pull/1563
=> Update CameraSensor.ccAllow HFOV narrower than 0.5°

tutorials/thermal_camera.md
This is an attempt to improve the documentation of the `<min_temp>`, `<max_temp>` and `<resolution>` tags in the thermal camera documentation.
After reading the description of `<min_temp>` and `<max_temp>` in the thermal camera tutorial I expected an output camera image value of `0` to mean `<min_temp>` Kelvin and a value of `2^bitDepth - 1` to mean `<max_temp>` Kelvin, so I was surprised to find out that that was not the case. Granted, the presence of the `<resolution>` tag did not really fit this mental model. It is also possible that this confusion was amplified by bugs that are now fixed (https://github.com/gazebosim/gz-rendering/pull/1133 and https://github.com/gazebosim/gz-rendering/pull/1138).
Nevertheless I tried to rephrase the descriptions a bit in an attempt to minimize the …
=> Clarify min and max temperature of thermal camera

include/gz/sensors/CameraSensor.hh, include/gz/sensors/Sensor.hh, src/CameraSensor.cc, src/Sensor.cc
Follow up to #525 
While fixing an issue with #525, I noticed several APIs that return `std::string` when it would be advantageous for them to return `const std::string &` instead, and easy since they already return a copy of member variable, which will now return a reference.
Changes the following methods:
* CameraSensor::InfoTopic()
* Sensor::Name()
* Sensor::FrameId()
* Sensor::Parent()
* Sensor::Topic()
=> Update API to return const references to strings

test/integration/boundingbox_camera.cc, test/integration/camera.cc, test/integration/depth_camera.cc, test/integration/gpu_lidar_sensor.cc, test/integration/rgbd_camera.cc, test/integration/segmentation_camera.cc, test/integration/thermal_camera.cc, test/integration/triggered_camera.cc
Related issue: https://github.com/gazebosim/gz-sensors/issues/503
Disables tests on Windows to reduce noise in CI
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Disable ign-sensors6's (fortress) failing tests on Windows

examples/loop_sensor/main.cc, include/gz/sensors/Manager.hh, src/BoundingBoxCameraSensor.cc, src/CameraSensor.cc, src/DepthCameraSensor.cc, src/GpuLidarSensor.cc, src/ImuSensor_TEST.cc, src/LogicalCameraSensor.cc, src/RgbdCameraSensor.cc, src/SegmentationCameraSensor.cc, src/ThermalCameraSensor.cc, src/WideAngleCameraSensor.cc
Fixes #<NUMBER>
Renderings sensors is a very powerful but also very controversial in terms of performance tool. In this patch I'd like to align profiler tooling for this type of sensors (some sensors already have desired instrumentation).
Now we can see callback execution time (copying is not free as expected) and publishing data (which is also some kind of copying).
And everything in between is a data conversion. I have some idea how to improve rtf, but it should be discussed first.
Also fixed some problems which came across (like to make CppCheck happy or similar)
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Better GZ_PROFILE instrumentation for rendering sensors

test/integration/dvl.cc, test/integration/force_torque.cc, test/integration/imu.cc, test/integration/magnetometer.cc, test/integration/rgbd_camera.cc
Upcoming changes in gz-transport(https://github.com/gazebosim/gz-transport/pull/665) cause build failures because the `gz/msgs/Utility.hh` wasn't included in some test.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Add missing includes
